// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackEnd.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("UnidadeFederacao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cnpj = "12345678910112",
                            Nome = "Cervejaria Top",
                            UnidadeFederacao = "Santa Catarina"
                        },
                        new
                        {
                            Id = 2,
                            Cnpj = "98765432121313",
                            Nome = "Sorveteria Japonesa",
                            UnidadeFederacao = "Santa Catarina"
                        },
                        new
                        {
                            Id = 3,
                            Cnpj = "45678912341525",
                            Nome = "Mercado Compre Mais",
                            UnidadeFederacao = "Santa Catarina"
                        },
                        new
                        {
                            Id = 4,
                            Cnpj = "78451236955441",
                            Nome = "Luminárias Do Sucesso",
                            UnidadeFederacao = "Santa Catarina"
                        },
                        new
                        {
                            Id = 5,
                            Cnpj = "26987453122447",
                            Nome = "Norte Calçados",
                            UnidadeFederacao = "Santa Catarina"
                        },
                        new
                        {
                            Id = 6,
                            Cnpj = "55577741233112",
                            Nome = "Alegria Musical",
                            UnidadeFederacao = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 7,
                            Cnpj = "22244498788994",
                            Nome = "Academia Do Conhecimento",
                            UnidadeFederacao = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 8,
                            Cnpj = "11177799911224",
                            Nome = "Batatão Alemão",
                            UnidadeFederacao = "São Paulo"
                        },
                        new
                        {
                            Id = 9,
                            Cnpj = "26987453122447",
                            Nome = "Livraria Mundo Bacana",
                            UnidadeFederacao = "São Paulo"
                        },
                        new
                        {
                            Id = 10,
                            Cnpj = "56421378954132",
                            Nome = "Chapéu Colorido",
                            UnidadeFederacao = "Bahia"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CnpjId")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<int>("TelefoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CnpjId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("TelefoneId");

                    b.ToTable("Fornecedors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CnpjId = 1,
                            Cpf = "12345678922",
                            DataCadastro = new DateTime(2011, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1989, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thiago@thiago.com",
                            EmpresaId = 1,
                            Idade = 32,
                            Nome = "Thiago",
                            Rg = "9871234563",
                            TelefoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            CnpjId = 1,
                            Cpf = "98765432111",
                            DataCadastro = new DateTime(2011, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1993, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucian@lucian.com",
                            EmpresaId = 1,
                            Idade = 28,
                            Nome = "Lucian",
                            Rg = "1234567899",
                            TelefoneId = 2
                        },
                        new
                        {
                            Id = 3,
                            CnpjId = 2,
                            Cpf = "45678912344",
                            DataCadastro = new DateTime(2015, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1999, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jaqueline@jaqueline.com",
                            EmpresaId = 2,
                            Idade = 22,
                            Nome = "Jaqueline",
                            Rg = "1748511236",
                            TelefoneId = 3
                        },
                        new
                        {
                            Id = 4,
                            CnpjId = 2,
                            Cpf = "32145698733",
                            DataCadastro = new DateTime(2015, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1996, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria@maria.com",
                            EmpresaId = 2,
                            Idade = 25,
                            Nome = "Maria",
                            Rg = "0144100255",
                            TelefoneId = 4
                        },
                        new
                        {
                            Id = 5,
                            CnpjId = 3,
                            Cpf = "87645921387",
                            DataCadastro = new DateTime(2019, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(2002, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "arthur@arthur.com",
                            EmpresaId = 3,
                            Idade = 19,
                            Nome = "Arthur",
                            Rg = "7899871599",
                            TelefoneId = 5
                        },
                        new
                        {
                            Id = 6,
                            CnpjId = 3,
                            Cpf = "79846513279",
                            DataCadastro = new DateTime(2019, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(2001, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gabrielle@gabrielle.com",
                            EmpresaId = 3,
                            Idade = 20,
                            Nome = "Gabrielle",
                            Rg = "1590590870",
                            TelefoneId = 6
                        },
                        new
                        {
                            Id = 7,
                            CnpjId = 4,
                            Cpf = "31264597843",
                            DataCadastro = new DateTime(2005, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1982, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david@david.com",
                            EmpresaId = 4,
                            Idade = 39,
                            Nome = "David",
                            Rg = "9806503024",
                            TelefoneId = 7
                        },
                        new
                        {
                            Id = 8,
                            CnpjId = 4,
                            Cpf = "21354687972",
                            DataCadastro = new DateTime(2005, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1984, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "robson@robson.com",
                            EmpresaId = 4,
                            Idade = 37,
                            Nome = "Robson",
                            Rg = "5302548951",
                            TelefoneId = 8
                        },
                        new
                        {
                            Id = 9,
                            CnpjId = 5,
                            Cpf = "95874543223",
                            DataCadastro = new DateTime(2009, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1986, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "diego@diego.com",
                            EmpresaId = 5,
                            Idade = 35,
                            Nome = "Diego",
                            Rg = "4870009870",
                            TelefoneId = 9
                        },
                        new
                        {
                            Id = 10,
                            CnpjId = 5,
                            Cpf = "65342178941",
                            DataCadastro = new DateTime(2009, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1994, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "roberto@roberto.com",
                            EmpresaId = 5,
                            Idade = 27,
                            Nome = "Roberto",
                            Rg = "5595585573",
                            TelefoneId = 10
                        },
                        new
                        {
                            Id = 11,
                            CnpjId = 6,
                            Cpf = "97594814724",
                            DataCadastro = new DateTime(2016, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1998, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "daisy@daisy.com",
                            EmpresaId = 6,
                            Idade = 23,
                            Nome = "Daisy",
                            Rg = "9632587419",
                            TelefoneId = 11
                        },
                        new
                        {
                            Id = 12,
                            CnpjId = 6,
                            Cpf = "23556889717",
                            DataCadastro = new DateTime(2016, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1994, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "camila@camila.com",
                            EmpresaId = 6,
                            Idade = 27,
                            Nome = "Camila",
                            Rg = "5465644566",
                            TelefoneId = 12
                        },
                        new
                        {
                            Id = 13,
                            CnpjId = 7,
                            Cpf = "74125896359",
                            DataCadastro = new DateTime(2017, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(2002, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pedro@pedro.com",
                            EmpresaId = 7,
                            Idade = 19,
                            Nome = "Pedro",
                            Rg = "3577535915",
                            TelefoneId = 13
                        },
                        new
                        {
                            Id = 14,
                            CnpjId = 7,
                            Cpf = "85274196369",
                            DataCadastro = new DateTime(2017, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1993, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "felipe@felipe.com",
                            EmpresaId = 7,
                            Idade = 28,
                            Nome = "Felipe",
                            Rg = "5438732102",
                            TelefoneId = 14
                        },
                        new
                        {
                            Id = 15,
                            CnpjId = 8,
                            Cpf = "02305809901",
                            DataCadastro = new DateTime(2013, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1992, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rhuan@rhuan.com",
                            EmpresaId = 8,
                            Idade = 29,
                            Nome = "Rhuan",
                            Rg = "2295584491",
                            TelefoneId = 15
                        },
                        new
                        {
                            Id = 16,
                            CnpjId = 8,
                            Cpf = "01475098088",
                            DataCadastro = new DateTime(2013, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1996, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manuelle@manuelle.com",
                            EmpresaId = 8,
                            Idade = 25,
                            Nome = "Manuelle",
                            Rg = "2699874563",
                            TelefoneId = 16
                        },
                        new
                        {
                            Id = 17,
                            CnpjId = 9,
                            Cpf = "32078094041",
                            DataCadastro = new DateTime(2009, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1998, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ademar@ademar.com",
                            EmpresaId = 9,
                            Idade = 23,
                            Nome = "Ademar",
                            Rg = "1221231251",
                            TelefoneId = 17
                        },
                        new
                        {
                            Id = 18,
                            CnpjId = 9,
                            Cpf = "51009548903",
                            DataCadastro = new DateTime(2007, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1991, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gustavo@gustavo.com",
                            EmpresaId = 9,
                            Idade = 30,
                            Nome = "Gustavo",
                            Rg = "2232242252",
                            TelefoneId = 18
                        },
                        new
                        {
                            Id = 19,
                            CnpjId = 10,
                            Cpf = "55077011037",
                            DataCadastro = new DateTime(2006, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1990, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marcia@marcia.com",
                            EmpresaId = 10,
                            Idade = 31,
                            Nome = "Marcia",
                            Rg = "7787797747",
                            TelefoneId = 19
                        },
                        new
                        {
                            Id = 20,
                            CnpjId = 10,
                            Cpf = "98078045012",
                            DataCadastro = new DateTime(2003, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1976, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "invonesio@invonesio.com",
                            EmpresaId = 10,
                            Idade = 45,
                            Nome = "Invonesio",
                            Rg = "0980331115",
                            TelefoneId = 20
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Telefones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Thiago",
                            NumeroTelefone = "(47)9 9214-7879"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Lucian",
                            NumeroTelefone = "(47)9 1234-4321"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Jaqueline",
                            NumeroTelefone = "(47)9 9091-9294"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Maria",
                            NumeroTelefone = "(47)9 2021-2324"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Arthur",
                            NumeroTelefone = "(47)9 3031-3235"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Gabrielle",
                            NumeroTelefone = "(47)9 5453-5759"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "David",
                            NumeroTelefone = "(47)9 7080-9050"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Robson",
                            NumeroTelefone = "(47)9 2010-4060"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Diego",
                            NumeroTelefone = "(47)9 7585-9555"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Roberto",
                            NumeroTelefone = "(47)9 7686-9612"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Daisy",
                            NumeroTelefone = "(21)9 0220-2059"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Camila",
                            NumeroTelefone = "(21)9 9319-3344"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Pedro",
                            NumeroTelefone = "(21)9 1598-7542"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Felipe",
                            NumeroTelefone = "(21)9 3331-1119"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Rhuan",
                            NumeroTelefone = "(11)9 2224-4445"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Manuelle",
                            NumeroTelefone = "(11)9 5570-5551"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Ademar",
                            NumeroTelefone = "(11)9 7997-0102"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Gustavo",
                            NumeroTelefone = "(11)9 9990-0005"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Marcia",
                            NumeroTelefone = "(71)9 9103-1250"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Invonesio",
                            NumeroTelefone = "(71)9 1444-2470"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Fornecedor", b =>
                {
                    b.HasOne("BackEnd.Models.Empresa", "Cnpj")
                        .WithMany()
                        .HasForeignKey("CnpjId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Telefone", "Telefone")
                        .WithMany()
                        .HasForeignKey("TelefoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cnpj");

                    b.Navigation("Empresa");

                    b.Navigation("Telefone");
                });
#pragma warning restore 612, 618
        }
    }
}
